# Generated by Django 5.1.7 on 2025-04-06 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_options_alter_animalpassport_options_and_more'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalservice',
            options={'verbose_name': 'Дополнительная услуга', 'verbose_name_plural': 'Дополнительные услуги'},
        ),
        migrations.AlterModelOptions(
            name='servicerecord',
            options={'verbose_name': 'Запись услуги', 'verbose_name_plural': 'Записи услуг'},
        ),
        migrations.AlterModelOptions(
            name='taskrecord',
            options={'verbose_name': 'Запись задачи', 'verbose_name_plural': 'Записи задач'},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Тип задачи', 'verbose_name_plural': 'Типы задач'},
        ),
        migrations.AddIndex(
            model_name='servicerecord',
            index=models.Index(fields=['service_date', 'service_time'], name='service_rec_service_ab443e_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerecord',
            index=models.Index(fields=['animal'], name='service_rec_animal__d1ac68_idx'),
        ),
        migrations.AddIndex(
            model_name='taskrecord',
            index=models.Index(fields=['task_date', 'task_time'], name='task_record_task_da_540ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='taskrecord',
            index=models.Index(fields=['user'], name='task_record_user_id_508cde_idx'),
        ),
        migrations.AlterModelTable(
            name='additionalservice',
            table='additional_services',
        ),
        migrations.AlterModelTable(
            name='servicerecord',
            table='service_records',
        ),
        migrations.AlterModelTable(
            name='taskrecord',
            table='task_records',
        ),
        migrations.AlterModelTable(
            name='tasktype',
            table='task_types',
        ),
    ]
