# Generated by Django 5.1.7 on 2025-04-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_organization_options_alter_permission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
    ]
