# Generated by Django 5.1.7 on 2025-04-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Гостиница', 'verbose_name_plural': 'Гостиницы'},
        ),
        migrations.AlterModelOptions(
            name='hotelpricing',
            options={'verbose_name': 'Тариф гостиницы', 'verbose_name_plural': 'Тарифы гостиниц'},
        ),
        migrations.AlterModelOptions(
            name='hotelrestriction',
            options={'verbose_name': 'Ограничение гостиницы', 'verbose_name_plural': 'Ограничения гостиниц'},
        ),
        migrations.AlterModelTable(
            name='hotel',
            table='hotels',
        ),
        migrations.AlterModelTable(
            name='hotelpricing',
            table='hotel_pricings',
        ),
        migrations.AlterModelTable(
            name='hotelrestriction',
            table='hotel_restrictions',
        ),
    ]
