# Generated by Django 5.1.7 on 2025-04-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodation',
            options={'verbose_name': 'Размещение', 'verbose_name_plural': 'Размещения'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelTable(
            name='accommodation',
            table='accommodations',
        ),
        migrations.AlterModelTable(
            name='booking',
            table='bookings',
        ),
    ]
